### ISSUE TITLE
Finalise MedGen xref table

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/medgen#15]
@joeflack4 

here some final changes to the medgen table (`medgen-xrefs.robot.template.tsv`):

- [x] MedGen repo changes https://github.com/monarch-initiative/medgen/pull/19
  - [x] Remove all rows with `MEDGENCUI` in it (we only need xrefs to MEDGEN:123 and UMLS:123)
  - [x] Add two new columns (see below)
  - [x] UMLS terms should have MEDGEN IDs as source, but not the other war around (MEDGEN terms should not have UMLS IDs as source). The reason is that the UMLS ids are, indeed, not evidence for the MEDGEN cross-reference!
  - [x] Add MONDO -> MESH mappings to `medgen-xrefs.robot.template.tsv`
- [x] Mondo repo: pull down new template and commit to Mondo https://github.com/monarch-initiative/mondo/pull/7467

| mondo_id      | xref_id              | source_id          | source_medgen_id          | mapping_predicate |
|---------------|----------------------|--------------------|--------------------|--------------------|
| ID            | A oboInOwl:hasDbXref | >A oboInOwl:source | >A oboInOwl:source | >A oboInOwl:source |
| MONDO:0021129 | MEDGEN:10033         |       | MONDO:MEDGEN      | MONDO:equivalentTo |
| MONDO:0005854 | MEDGEN:10069         |       | MONDO:MEDGEN      | MONDO:equivalentTo |
| MONDO:0009642 | MEDGEN:10077         |      | MONDO:MEDGEN      | MONDO:equivalentTo |
| MONDO:0005855 | UMLS:C0026393         |   MEDGEN:10081    | MONDO:MEDGEN      | MONDO:equivalentTo |
| MONDO:0002274 | UMLS:C0026471     | MEDGEN:10088       | MONDO:MEDGEN      | MONDO:equivalentTo |

**Comment by joeflack4** [comment]
Sounds good! I'll start on this before the ICD11 work, hopefully this week.
_edit_: That changed to be between first and 2nd ICD11 PR.

**Comment by matentzn** [comment]
I add another action item to this issue: please add MONDO->MESH mappings to the ROBOT template with the exact same logic and metadata as the MONDO -> UMLS ones.

**Comment by joeflack4** [comment]
_Edit: Moved comment into PR discussion:_
- _https://github.com/monarch-initiative/medgen/pull/19#discussion_r1536902813_
