### ISSUE TITLE
Add HPO<->UMLS and HPO<->MeSH mapping to MedGen release

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/medgen#16]
Context here: https://github.com/obophenotype/human-phenotype-ontology/issues/9750

We need the two mappings as SSSOM files, we will serve them throught the Monarch Mapping Commons.

@joeflack4 give me a sense if you will be able to do this quickly or if this will take you more than 1 or 2 hours. If the former, I would suggest to couple this issue with #15 and do them both at once. @twhetzel do you agree? Both these issues require processing of the same file (MedgenIDMappings). If the latter, i.e. it will likely take you more than 2 hours, please let me know before you attempt to tackle this.

**Comment by joeflack4** [comment]
Yes, it seems doable in less than 2 hours. I just spent 20 minutes reading up on this, had to skip most of https://github.com/obophenotype/human-phenotype-ontology/issues/9750, it's more than I need to know. I lost my MedGen environment when my PC died so I had to set a few things up. It sounds like this one can come before #15  and before https://github.com/monarch-initiative/mondo-ingest/pull/412 then. I should be able to start on this tomorrow or Thursday.
_Edit_: I heard a priority update on this; will do this in between my two ICD11 PRs.
