### ISSUE TITLE
Add OWL2 representation

### ISSUE THREAD

**Issue by jamesamcl** [monarch-initiative/medgen#30]
It would be nice to have an OWL2 RDF/XML representation alongside the OBO file. Then we can add medgen to OLS.

**Comment by joeflack4** [comment]
That sounds like a great idea!

**Comment by joeflack4** [comment]
Hey @jamesamcl, unfortunately this is a bigger ask than I realized. It was just a couple lines to add the `robot convert` step, but the problem is file size. While `medgen.obo` is ~450mb, my local `medgen.owl` is so 2.7g. Similarly the `medgen-disease-extract.obo` is 200mb but the `medgen-disease-extract.owl` is 2.2g. These sizes are greater than can be uploaded to GitHub releases (2g).

I wonder if the problem could be solved simply by minifying. I've never done this to XML, personally, much less RDF/XML. 

Do you know if OLS supports any other formats? I wonder if there are any others that would be small enough when converted.

**Comment by jamesamcl** [comment]
I think the easiest option would be to gzip it and add support to OLS for gzipped files. I’ll open an issue on OLS and cross reference. Thanks so much for looking into this!

**Comment by joeflack4** [comment]
Oh, OK cool! I like this solution. Looks like you've already made some headway. I'll implement that on this side shortly.

**Comment by joeflack4** [comment]
Hey @jamesamcl, I tried to set us up for `.owl.gz` today, but the GH action [is failing](https://github.com/monarch-initiative/medgen/actions/runs/11395948209/job/31708974840). I forgot, there is a blocker:
- #8 
- Related: #10

I tried `macos` as well, which has more memory than `ubuntu`, but still no go.

I could potentially try using some alternative [robot convert](https://robot.obolibrary.org/convert) formats. I think it will have the same problem though. If you want, I could give it a go, though. Do you know if OLS would support any of these other formats?

I know won't support this format:
- obo - [OBO Format](http://purl.obolibrary.org/obo/oboformat)

Tried already but running out of memory:
- json - [OBO Graphs JSON](https://github.com/geneontology/obographs/)
- owl - [RDF/XML](https://www.w3.org/TR/rdf-syntax-grammar/)

Haven't tried yet, though I imagine will have the same problem:
- ofn - [OWL Functional](http://www.w3.org/TR/owl2-syntax/)
- omn - [Manchester](https://www.w3.org/TR/owl2-manchester-syntax/)
- owx - [OWL/XML](https://www.w3.org/TR/owl2-xml-serialization/)
- ttl - [Turtle](https://www.w3.org/TR/turtle/)

**Comment by joeflack4** [comment]
@twhetzel FYI I spent a short amount of time on this but hit a block due to memory issues. If you happen to know an alternate way to do a conversion and use less memory, let me know.

I could possibly try `owltools` instead, but I'm not optimistic it'll solve.

**Comment by jamesamcl** [comment]
I just tried locally:

`robot convert --input medgen.obo --output medgen.owl` peaked at 16.1 GB
`robot convert --input medgen.obo --output medgen.ttl` peaked at 14.5 GB

So it seems like ttl might get us just under the memory ceiling which is apparently 16 GB for a standard GitHub runner. Turtle is supported by OLS.

**Comment by joeflack4** [comment]
Thanks for looking into this! That's great to see that `.ttl` is clocking in under that limit; hopefully that remains consistent.

Last time I looked into runners, I think the [memory limits](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners) were a lot lower. Perhaps we can manage!

---

I changed the runner back to `ubuntu` which has the 16G memory, but unfortunately for whatever reason it's [still running out of memory in the action](https://github.com/monarch-initiative/medgen/actions/runs/11410471330/job/31752849731).

Other options:
a. **FastOBO**: Chris recommended but I haven't looked into.
b. **Smaller structure**: Nico: 
> I think in this case the best way to deal with the memory issue is to drastically reduce the size of the medgen dump you load into OLS: just labels, xrefs and subclass. That should shrink the size
c. **`ROBOT_JAVA_ARGS`**

**Comment by balhoff** [comment]
@joeflack4 are you setting the max heap size? This succeeded for me:

```
export ROBOT_JAVA_ARGS=-Xmx12G
robot convert -i medgen.obo -o medgen.ttl
```

**Comment by joeflack4** [comment]
I was thinking of trying that, but in the past when I've tried that with `robot` I've had it still run out of memory. But perhaps you're right! I'll give it a go.

**Comment by balhoff** [comment]
@joeflack4 for Java programs I would never leave that to chance, but have to make sure it fits within the machine you're running on. There is some overhead so always make it less than the actual RAM.

**Comment by joeflack4** [comment]
Yeah, I'm not sure why this hasn't helped in the past. Perhaps because what I was running just required way too much memory, and couldn't be set to the threshold I wanted.

In any case, good news is that it worked this time!:
- https://github.com/monarch-initiative/medgen/releases/tag/2024-10-19
